
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::307223751858:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-98b7THdb73aY
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::307223751858:user/kishore
      username: kishore  
    #   - roboshop-admin
    #   userarn: arn:aws:iam::307223751858:user/ramesh
    #   username: ramesh  
    #   - groups:
    #   - roboshop-trainee
    #   userarn: arn:aws:iam::160885265516:user/john
    #   username: john
    # - groups:
    #   - roboshop-trainee
    #   userarn: arn:aws:iam::160885265516:user/rahim
    #   username: rahim
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-03T04:03:09Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1217"
  uid: 3dfdf8ad-69f0-489f-9c09-7d36f8a3d740