
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::307223751858:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-TE3xOvinqt3I
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::307223751858:user/suresh
      username: suresh    
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-27T05:56:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1144"
  uid: 27194f72-a4e5-4a0a-8d6f-e89aabaa25b0
