
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::307223751858:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-qapebF7LdFST
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::307223751858:user/suresh
      username: suresh    
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-30T06:02:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1047"
  uid: 908608e2-7ee8-4ecf-bd2b-6505841ca771